export const inBuildSkills = {
  technicalSkills: [
    "ReactJS",
    "NodeJS",
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "MongoDB",
    "ExpressJS",
    "Redux",
    "GraphQL",
    "NextJS",
    "VueJS",
    "Angular",
    "SASS",
    "TailwindCSS",
    "REST API",
    "Git",
    "Docker",
    "Kubernetes",
    "AWS",
    "Jenkins",
    "Webpack",
    "Babel",
    "Java",
    "Spring Boot",
    "Python",
    "Django",
    "Flask",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "Firebase",
    "Linux",
    "CI/CD",
  ],
  softSkills: [
    "Communication",
    "TeamWork",
    "Problem-Solving",
    "Critical Thinking",
    "Adaptability",
    "Leadership",
    "Time Management",
    "Creativity",
    "Conflict Resolution",
    "Decision-Making",
    "Empathy",
    "Collaboration",
    "Work Ethic",
    "Active Listening",
    "Emotional Intelligence",
    "Negotiation",
    "Interpersonal Skills",
    "Presentation Skills",
    "Project Management",
    "Self-Motivation",
  ],
};
